update: contactUs page
she-code-africa/stem-a-girl-fe pull request #19
Opened 2024-07-17 13:26 UTC by HeemahMuslad

2024-07-19 15:04 UTC, Lezette requested changes
Codes and similar items are meant to be secret keys this should not be used inside the code, add it to an env file then use the variable.

When you're done, reach out to Eniola and inform her that they need to update the env file from the deployed page as well.

2024-07-19 15:04 UTC, Lezette commented on src/components/Recaptcha.jsx
> +          .execute("6LeMShEqAAAAANL4rT2yerYM70w-yM_HPi4TvrEP", { action: "submit" })
Add the key to an env file and use it. This is a key that should not be exposed to everyone

2024-07-19 15:04 UTC, Lezette commented on src/components/Recaptcha.jsx
> +  return <div ref={recaptchaRef} className="g-recaptcha" data-sitekey="6LeMShEqAAAAANL4rT2yerYM70w-yM_HPi4TvrEP" data-size="invisible"></div>;
Same thing here

2024-07-19 15:04 UTC, Lezette commented on src/components/contact-us/index.jsx
> +        .execute("6LeMShEqAAAAANL4rT2yerYM70w-yM_HPi4TvrEP")
And here

2024-07-19 15:04 UTC, Lezette commented on src/components/Recaptcha.jsx
> +    script.src = "https://www.google.com/recaptcha/api.js?render=6LeMShEqAAAAANL4rT2yerYM70w-yM_HPi4TvrEP";
Remove the code, add it to the .env file and call the env variable here to use it

2024-07-19 17:05 UTC, HeemahMuslad commented
https://www.loom.com/share/f1cd855bd3bc4693b072afd8222f6bdc

2024-07-19 19:09 UTC, Lezette approved these changes
LGTM

2024-07-19 19:09 UTC, Lezette approved these changes

2024-07-20 05:50 UTC, EseAlli approved these changes

2024-07-20 05:51 UTC, merged